### ISSUE TITLE
How about some idea for hprose(especially for hprose-java) H.A 

### ISSUE THREAD

**Issue by bwzhang2011** [hprose/hprose-java#9]
hprose is perfect for its simplicity and performance but lack of some H.A way like dubbo or commonrpc as for the latter on please pay a visit to http://git.oschina.net/284520459/commonrpc/wikis/home.  I think hprose could add some support like hprose-ha to provide H.A support and I dare say it's better enhance for it than multiple languages support.

**Comment by andot** [comment]
This is a good idea, and many people ask me to add those features. I have already had this plan many years ago. But I have no time to do it. Do you want to help me to implement it?

**Comment by bwzhang2011** [comment]
@andot, it's better you could make some interfaces for us to learn or implement and hope more could provide their solutions for based on such branch to make the special one.

**Comment by andot** [comment]
Tell me the details of which interfaces you want, or I don't know how to provide what you want.

for example: https://www.python.org/dev/peps/

**Comment by bwzhang2011** [comment]
@andot, commonrpc has provide some idea for ha support to be integrated with zookeeper but I could not quite grasp that which just gave birth to some idea that came across. if you have spare time you could find some idea for zookeeper integration. currently there's some datagrid solution as hazelcast which provides self-defned service support which I could say to do some work for hprose integration but just some idea. in all, I think hprose could make more integration with zookeeper or data-grid to make it horizontal.

**Comment by bwzhang2011** [comment]
for commonrpc, please take a vist to  http://git.oschina.net/284520459/commonrpc and especially for the commonrpc-manager chapter.

**Comment by andot** [comment]
I don't want to integrate any other things in hprose, because I hope it has no dependence.

Hprose is an open source project, any one can use and modify it. So if you want to integration some thing, you can do it by yourself. 

If you have some difficulties to integrate something, such as lacking the necessary interface in hprose, you can write out your desired interface to me.

**Comment by bwzhang2011** [comment]
@andot, maybe you misunderstood what I talked about and suggested. my suggestion is to add some integration like zookeeper for H.A use cases and it would be provided officially to reduce the error while not fully understand the hprose rpc design. I think it would not induce any overload modification to hprose itself but just some enhancement for it will turn and support the H.A to become distributed rpc solution.

**Comment by andot** [comment]
I know what you said. but I don't want to add some thing like this:

```java
import org.apache.zookeeper.ZooKeeper;
```

in hprose.

I hope hprose has no dependence.

**Comment by bwzhang2011** [comment]
@andot, my suggestion is to provide hprose-ha project for us to put into practice in our project or you could add some abstract definition for us to extend or implement without strong rely on zookeeper or not no matter what the actual name is but the purpose for hprose distributed expand.

**Comment by andot** [comment]
If you want to start a hprose-ha project, I can add you into this organization. Then you can create hprose-ha project in https://github.com/hprose by yourself.

If you want me to add some abstract definition to extend or implement without strong rely on zookeeper or something, you need provide the the details of them. otherwise, I don't what abstract definition should be added.

If you know how to do that, you can also do it by yourself, then push your request to this project. I will be glad to merge it. Thank you.

**Comment by TuWei1992** [comment]
都是中国人, 就别彪英语了吧😢

**Comment by andot** [comment]
嗯，如果谁有时间可以研究一下 dubbo，只要写一个简单的 dubbo 适配器，比如叫：dubbo-rpc-hprose，这些 HA 的特征就都有了，不需要自己从头开始写。
